# Generated by Django 3.2.2 on 2021-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invSystem', '0002_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Bob', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Bobby', max_length=50),
            preserve_default=False,
        ),
    ]
