# Generated by Django 3.2.2 on 2021-05-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invSystem', '0003_auto_20210510_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('item_quantity', models.IntegerField()),
            ],
        ),
    ]
