# Generated by Django 3.2.2 on 2021-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invSystem', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_catergories',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Fruit', 'Fruit'), ('Veg', 'Veg'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Pantry', 'Pantry'), ('Tinned', 'Tinned')], default='Veg', max_length=50),
            preserve_default=False,
        ),
    ]
